name: Lighthouse

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{github.token}}
  NODE_VERSION: '14.1'
  JOB_URL: 'https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
  STATUS_DESCRIPTION: 'Lighthouse SEO'

jobs:
  seo:
    name: SEO
    #    if: contains(github.ref, 'seo')
    runs-on: ubuntu-latest
    env:
      AURA: zattoo
      PROJECT: seo
    steps:
      - name: Announce
        uses: sibz/github-status-action@v1
        with:
          authToken: ${{env.GITHUB_TOKEN}}
          context: 'lighthouse'
          state: 'pending'
          target_url: ${{env.JOB_URL}}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-node-
      - run: npm install -g @lhci/cli@0.5.x
      - name: Run Lighthouse CI
        run: lhci autorun --config=projects/${{env.PROJECT}}/config/lighthouse.json
      - name: Success
        if: success()
        uses: sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'lighthouse'
          state: 'success'
          target_url: ${{env.GITHUB_TOKEN}}
      - name: Failure
        if: failure()
        uses: sibz/github-status-action@v1
        with:
          authToken: ${{env.GITHUB_TOKEN}}
          context: 'lighthouse'
          state: 'failure'
          target_url: ${{env.JOB_URL}}
